package core;

/**
 * Created by David on 03/04/2018.
 */
public enum Tool {
  CLASS, ABSTRACT_CLASS, INTERFACE_CLASS, RELATION, INHERIT_RELATION,
  INTERFACE_RELATION, AGGREGATION_RELATION, COMPOSITION_RELATION, ANY;
}
